import Link from 'next/link'
import {ChevronDown, FileText, Home, Landmark, ShieldCheck, Sparkles, WalletCards} from 'lucide-react'
import {Button} from '@/components/ui/button'
import type {ParsedClue} from '@/lib/types'

export function ClueNewPcPage({prefix, profileId, parsed, content}: {prefix: string; profileId: string; parsed: ParsedClue[]; content: string}) {
  const first = parsed[0]
  return (
    <section className="hidden min-h-screen w-full bg-[radial-gradient(circle_at_90%_18%,rgba(139,92,246,0.18),transparent_24%),linear-gradient(180deg,#ffffff,#f8fbff)] lg:block">
      <header className="flex h-20 w-full items-center justify-between border-b bg-white/80 px-10 backdrop-blur"><Link href={`${prefix}/profiles/${profileId}`} className="text-2xl font-black">AI 财富观察档案</Link><div className="text-lg font-semibold text-slate-500">让每一条线索，成就更清晰的财富认知</div><nav className="flex items-center gap-10 text-lg font-bold"><span>功能介绍</span><span>使用指南</span><span>定价</span><button className="rounded-xl border px-7 py-3">登录</button><button className="rounded-xl bg-gradient-to-r from-blue-600 to-violet-600 px-7 py-3 text-white">开始使用</button></nav></header>
      <div className="w-full px-28 py-16"><div className="text-center"><h1 className="text-6xl font-black tracking-tight">添加线索</h1><p className="mt-6 text-2xl text-slate-500">用自然语言记录你的财富相关信息，AI 将为你智能解析并归档管理。</p></div>
        <div className="mt-16 grid w-full grid-cols-2 gap-10"><section className="rounded-[28px] border bg-white p-8 shadow-panel"><div className="mb-8 flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-violet-50 text-violet-600"><FileText /></span><div><h2 className="text-2xl font-black">记录你的线索</h2><p className="text-slate-500">越详细，AI 识别越精准</p></div></div><div className="mb-6 grid grid-cols-6 gap-4">{['资产','负债','收入','家庭','消费','其他'].map((item, index) => <button key={item} className={index === 0 ? 'rounded-xl border border-violet-500 bg-violet-50 py-3 font-bold text-violet-600' : 'rounded-xl border py-3 font-bold text-slate-500'}>{item}</button>)}</div><textarea className="h-60 w-full resize-none rounded-2xl border border-violet-200 p-6 text-xl leading-9 outline-none" defaultValue={content} /><Button className="mt-8 h-16 w-full rounded-2xl text-2xl font-black"><Sparkles /> AI解析</Button><p className="mt-5 text-center text-slate-400">内容仅用于解析与归档，严格保护隐私</p></section>
        <section className="rounded-[28px] border bg-white p-8 shadow-panel"><div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-4"><Sparkles className="h-8 w-8 text-violet-600" /><div><h2 className="text-2xl font-black">AI 解析结果</h2><p className="text-slate-500">确认无误后将自动归档</p></div></div><span className="rounded-xl bg-emerald-50 px-6 py-3 text-xl font-black text-emerald-600">置信度 92%</span></div><div className="rounded-2xl border p-8"><div className="mb-8 inline-flex items-center gap-2 rounded-xl bg-blue-50 px-4 py-2 font-black text-blue-600"><WalletCards /> 资产 · 股票</div><dl className="grid grid-cols-[120px_1fr] gap-y-6 text-lg"><dt className="text-slate-500">资产名称</dt><dd>{first?.item ?? '腾讯控股（0700.HK）'}</dd><dt className="text-slate-500">相关描述</dt><dd>{first?.explanation ?? '买入腾讯股票1000股'}</dd><dt className="text-slate-500">数量</dt><dd>{first?.amountText ?? '1000 股'}</dd><dt className="text-slate-500">来源</dt><dd>手动输入</dd></dl><div className="mt-8 rounded-2xl bg-emerald-50 p-8 text-center"><div className="text-slate-500">预计影响</div><div className="mt-3 text-4xl font-black text-emerald-600">+32,000 元</div></div></div><div className="mt-6 flex justify-between"><button className="font-bold text-primary">查看原文 <ChevronDown className="inline h-4 w-4" /></button><div className="flex gap-4"><button className="rounded-xl border px-8 py-4 font-bold">重新解析</button><button className="rounded-xl bg-primary px-8 py-4 font-bold text-white">确认并保存</button></div></div></section></div>
        <footer className="mt-10 grid grid-cols-3 rounded-2xl border bg-white/70 p-6 text-center"><div><ShieldCheck className="mx-auto text-violet-600" />隐私安全</div><div><Landmark className="mx-auto text-violet-600" />智能理解</div><div><Home className="mx-auto text-violet-600" />持续进化</div></footer>
      </div>
    </section>
  )
}
