'use client'

import {Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts'

const palette = ['#6366f1', '#10b981', '#8b5cf6', '#f97316', '#f59e0b', '#64748b']

export function LineCompareChart({data, lines, compact=false}: {data: readonly any[]; lines: {key: string; name: string; color?: string}[]; compact?: boolean}) {return <div className={compact ? 'h-44' : 'h-72'}><ResponsiveContainer><LineChart data={data} margin={compact ? {left: -18, right: 6, top: 8, bottom: 0} : undefined}><CartesianGrid strokeDasharray="4 4" stroke="#e2e8f0"/><XAxis dataKey="year" tick={{fontSize: compact ? 11 : 12}}/><YAxis tick={{fontSize: compact ? 11 : 12}}/><Tooltip formatter={(v)=>Number(v).toLocaleString('zh-CN')}/>{!compact && <Legend/>}{lines.map((line,i)=><Line type="monotone" dataKey={line.key} name={line.name} stroke={line.color ?? palette[i]} strokeWidth={3} dot={!compact} key={line.key}/>)}</LineChart></ResponsiveContainer></div>}
export function AreaTrendChart({data, compact=false}: {data: readonly any[]; compact?: boolean}) {return <div className={compact ? 'h-44' : 'h-72'}><ResponsiveContainer><AreaChart data={data}><defs><linearGradient id="value" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#6366f1" stopOpacity={0.28}/><stop offset="95%" stopColor="#6366f1" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="4 4" stroke="#e2e8f0"/><XAxis dataKey="year"/><YAxis/><Tooltip formatter={(v)=>Number(v).toLocaleString('zh-CN')}/><Area dataKey="value" name="资产" stroke="#6366f1" fill="url(#value)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div>}
export function StackedCostChart({data, compact=false}: {data: readonly any[]; compact?: boolean}) {return <div className={compact ? 'h-44' : 'h-72'}><ResponsiveContainer><BarChart data={data} margin={compact ? {left: -18, right: 4, top: 8, bottom: 0} : undefined}><CartesianGrid strokeDasharray="4 4" stroke="#e2e8f0"/><XAxis dataKey="city" tick={{fontSize: compact ? 11 : 12}}/><YAxis tick={{fontSize: compact ? 11 : 12}}/><Tooltip formatter={(v)=>Number(v).toLocaleString('zh-CN')}/>{!compact && <Legend/>}<Bar dataKey="rent" name="住房" stackId="a" fill="#60a5fa"/><Bar dataKey="food" name="饮食" stackId="a" fill="#6ee7b7"/><Bar dataKey="transport" name="交通" stackId="a" fill="#fdba74"/><Bar dataKey="taxAndInsurance" name="税费社保" stackId="a" fill="#a78bfa"/><Bar dataKey="other" name="其他" stackId="a" fill="#cbd5e1"/></BarChart></ResponsiveContainer></div>}
export function AllocationPie({data, compact=false}: {data: readonly {name: string; weight: number}[]; compact?: boolean}) {return <div className={compact ? 'h-44' : 'h-72'}><ResponsiveContainer><PieChart><Pie data={data} dataKey="weight" nameKey="name" innerRadius={compact ? 42 : 58} outerRadius={compact ? 68 : 92} paddingAngle={3}>{data.map((_,i)=><Cell fill={palette[i % palette.length]} key={i}/>)}</Pie><Tooltip formatter={(v)=>`${v}%`}/><Legend wrapperStyle={{fontSize: compact ? 12 : 14}}/></PieChart></ResponsiveContainer></div>}
