'use client'

import {Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts'

const palette = ['#2563eb', '#10b981', '#8b5cf6', '#f97316', '#f59e0b', '#64748b']

export function LineCompareChart({data, lines}: {data: readonly any[]; lines: {key: string; name: string; color?: string}[]}) {return <div className="h-72 min-w-0"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="4 4" stroke="#e2e8f0"/><XAxis dataKey="year"/><YAxis/><Tooltip formatter={(v)=>Number(v).toLocaleString('zh-CN')}/><Legend/>{lines.map((line,i)=><Line type="monotone" dataKey={line.key} name={line.name} stroke={line.color ?? palette[i]} strokeWidth={3} dot={false} key={line.key}/>)}</LineChart></ResponsiveContainer></div>}
export function AreaTrendChart({data}: {data: readonly any[]}) {return <div className="h-72 min-w-0"><ResponsiveContainer><AreaChart data={data}><defs><linearGradient id="value" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#2563eb" stopOpacity={0.28}/><stop offset="95%" stopColor="#2563eb" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="4 4" stroke="#e2e8f0"/><XAxis dataKey="year"/><YAxis/><Tooltip formatter={(v)=>Number(v).toLocaleString('zh-CN')}/><Area dataKey="value" name="资产" stroke="#2563eb" fill="url(#value)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div>}
export function StackedCostChart({data}: {data: readonly any[]}) {return <div className="h-72 min-w-0"><ResponsiveContainer><BarChart data={data}><CartesianGrid strokeDasharray="4 4" stroke="#e2e8f0"/><XAxis dataKey="city"/><YAxis/><Tooltip formatter={(v)=>Number(v).toLocaleString('zh-CN')}/><Legend/><Bar dataKey="rent" name="住房" stackId="a" fill="#60a5fa"/><Bar dataKey="food" name="饮食" stackId="a" fill="#6ee7b7"/><Bar dataKey="transport" name="交通" stackId="a" fill="#fdba74"/><Bar dataKey="taxAndInsurance" name="税费社保" stackId="a" fill="#a78bfa"/><Bar dataKey="other" name="其他" stackId="a" fill="#cbd5e1"/></BarChart></ResponsiveContainer></div>}
export function AllocationPie({data}: {data: readonly {name: string; weight: number}[]}) {return <div className="h-72 min-w-0"><ResponsiveContainer><PieChart><Pie data={data} dataKey="weight" nameKey="name" innerRadius={58} outerRadius={92} paddingAngle={3}>{data.map((_,i)=><Cell fill={palette[i % palette.length]} key={i}/>)}</Pie><Tooltip formatter={(v)=>`${v}%`}/><Legend/></PieChart></ResponsiveContainer></div>}
