import Link from 'next/link'
import {RefreshCw, Star} from 'lucide-react'
import {AreaTrendChart, AllocationPie, LineCompareChart, StackedCostChart} from './Charts'
import {DataTable, InsightCard, KpiCard, Money, PageHero, Panel, ParameterBar, ScenarioTabs, Shell} from './Ui'
import {buyRentData} from '@/mock/buyRent.mock'
import {investmentData} from '@/mock/investment.mock'
import {livingCostData} from '@/mock/livingCost.mock'
import {retirementData} from '@/mock/retirement.mock'
import {personalAssetData} from '@/mock/personalAsset.mock'
import type {ScenarioModule} from '@/lib/types'

const money = (value: number) => `¥${value.toLocaleString('zh-CN')}`
const percent = (value: number) => `${(value * 100).toFixed(value < 0.1 ? 1 : 0)}%`

export function FinanceModulePage({module}: {module: ScenarioModule}) {
  if (module === 'buy_rent') return <BuyRentPage />
  if (module === 'investment') return <InvestmentPage />
  if (module === 'living_cost') return <LivingCostPage />
  if (module === 'retirement') return <RetirementPage />
  return <PersonalPage />
}

function BuyRentPage() {
  const d = buyRentData
  return <Shell><PageHero title="买房 vs 租房决策" subtitle="基于当前假设，对比两种居住方案在 10/20/30 年后的总成本、净资产和风险。" actions={<div className="flex gap-3"><button className="rounded-xl border bg-white px-5 py-3 font-bold"><RefreshCw className="mr-2 inline" size={16}/>重新计算</button><button className="rounded-xl border bg-white px-5 py-3 font-bold"><Star className="mr-2 inline" size={16}/>收藏方案</button></div>}/><section className="grid gap-5 lg:grid-cols-2"><KpiCard label="买房方案" value={`总成本 ${money(d.output.buy.totalCost)}`} hint={`月供 ${money(d.output.buy.monthlyPayment)} / 月；净资产增长 ${money(d.output.buy.netAssetGrowth)}`}/><KpiCard label="租房方案" value={`总成本 ${money(d.output.rent.totalRentPaid)}`} hint={`月租 ${money(d.input.monthlyRent)} / 月；净资产增长 ${money(d.output.rent.netAssetGrowth)}`} tone="green"/></section><div className="mt-5"><ParameterBar items={[['房价', money(d.input.housePrice)], ['首付', percent(d.input.downPaymentRatio)], ['利率', percent(d.input.mortgageRate)], ['房价涨幅', percent(d.input.houseGrowthRate)], ['租金', `${money(d.input.monthlyRent)}/月`], ['投资收益', percent(d.input.investmentReturn)], ['年限', `${d.input.years} 年`]].map(([label, value]) => ({label, value}))}/></div><section className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_1fr]"><Panel><h2 className="mb-4 text-xl font-bold">买房净资产 vs 租房投资资产</h2><LineCompareChart data={d.output.chart} lines={[{key:'buyNetAsset',name:'买房净资产'},{key:'rentNetAsset',name:'租房投资资产',color:'#10b981'}]}/></Panel><div className="grid gap-5"><Panel><h3 className="mb-4 font-bold">房产价值 / 剩余贷款 / 租房支出</h3><LineCompareChart data={d.output.chart} lines={[{key:'propertyValue',name:'房产价值'},{key:'remainingLoan',name:'剩余贷款',color:'#f97316'},{key:'rentPaid',name:'累计租金',color:'#8b5cf6'}]}/></Panel></div></section><Panel className="mt-5"><DataTable headers={["维度", "买房", "租房"]} rows={[["总成本", money(d.output.buy.totalCost), money(d.output.rent.totalRentPaid)], ["最终资产", money(d.output.buy.finalPropertyValue), money(d.output.rent.finalInvestmentAsset)], ["灵活性", "较低", "高"], ["风险", "中等：利率与房价波动", "较低：保留迁移弹性"]]}/></Panel><InsightCard><h3 className="text-xl font-bold">{d.output.winner === 'rent' ? '租房方案更优' : '买房方案更优'}</h3><p className="mt-2 text-slate-600">当前 mock 假设下，{d.output.winner === 'rent' ? '租房并投资' : '买房持有'}方案预计多获得 <b className="text-emerald-600">{money(d.output.diff)}</b> 净资产。</p><button className="mt-4 rounded-xl border bg-white px-4 py-2 text-sm font-bold">查看详细分析</button></InsightCard></Shell>
}

function InvestmentPage(){const d=investmentData; return <Shell><PageHero title="投资协助" subtitle="展示不同资产配置下的未来收益、风险和资产曲线。"/><ScenarioTabs items={["保守型", "平衡型", "进取型"]} active="平衡型"/><section className="mt-5 grid gap-5 lg:grid-cols-2"><Panel><h2 className="mb-4 text-xl font-bold">资产配置环形图</h2><AllocationPie data={d.scenario.assets.map(a=>({name:a.name,weight:a.weight}))}/></Panel><div className="grid gap-5"><KpiCard label="预计年化收益" value={`${percent(d.output.expectedAnnualReturn)} - 8.4%`} tone="green"/><KpiCard label="最终资产 / 累计收益" value={money(d.output.finalAsset)} hint={`累计投入 ${money(d.output.totalInvested)}；收益 ${money(d.output.profit)}`} tone="purple"/></div></section><Panel className="mt-5"><h2 className="mb-4 text-xl font-bold">未来资产增长曲线</h2><LineCompareChart data={d.output.chart} lines={[{key:'conservative',name:'保守'},{key:'value',name:'基准'},{key:'optimistic',name:'乐观',color:'#8b5cf6'}]}/></Panel><InsightCard><h3 className="text-xl font-bold">风险说明</h3><p className="mt-2 text-slate-600">风险评分 {d.output.riskScore}/100；平衡配置适合希望长期增值、可承受阶段性回撤的人群。</p></InsightCard></Shell>}

function LivingCostPage(){const d=livingCostData; return <Shell><PageHero title="城市生活成本" subtitle="对比不同城市的居住、饮食、交通、税费成本，并计算可负担程度。"/><ScenarioTabs items={d.scenario.cities.map(c=>c.city)} active={d.input.selectedCity}/><section className="mt-5 grid gap-5 lg:grid-cols-2"><KpiCard label="月度总成本" value={money(d.output.selectedCityTotalCost)} hint={`当前城市：${d.input.selectedCity}`}/><KpiCard label="可负担指数" value={`${d.output.affordabilityScore} / 100`} hint={`储蓄率 ${d.output.savingRate}%`} tone="green"/></section><Panel className="mt-5"><h2 className="mb-4 text-xl font-bold">居住 / 饮食 / 交通 / 税费 / 其他</h2><StackedCostChart data={d.output.chart}/></Panel><Panel className="mt-5"><DataTable headers={["城市", "居住", "饮食", "交通", "税费", "其他", "月总成本"]} rows={d.scenario.cities.map(c=>[c.city, money(c.rent), money(c.food), money(c.transport), money(c.taxAndInsurance), money(c.entertainment+c.other), money(c.rent+c.food+c.transport+c.taxAndInsurance+c.entertainment+c.other)])}/></Panel></Shell>}

function RetirementPage(){const d=retirementData; return <Shell><PageHero title="退休计划" subtitle="估算退休所需资产、退休后资金变化和耗尽年龄。"/><ScenarioTabs items={["55岁退休", "60岁退休", "65岁退休"]} active={`${d.input.retirementAge}岁退休`}/><section className="mt-5 grid gap-5 lg:grid-cols-2"><KpiCard label="退休所需资金" value={money(d.output.requiredFund)} tone="green"/><KpiCard label="资金耗尽年龄" value={`${Math.round(d.output.depletionAge)} 岁`} hint={`预期寿命 ${d.scenario.lifeExpectancy} 岁`} tone="orange"/></section><Panel className="mt-5"><h2 className="mb-4 text-xl font-bold">退休资产增长 / 消耗曲线</h2><LineCompareChart data={d.output.chart.map(x=>({...x, value:x.asset}))} lines={[{key:'value',name:'资产'},{key:'expense',name:'年度支出',color:'#f97316'}]}/></Panel><Panel className="mt-5"><DataTable headers={["项目", "数值"]} rows={[["当前年龄", `${d.input.currentAge} 岁`], ["退休年龄", `${d.input.retirementAge} 岁`], ["当前资产", money(d.input.currentAsset)], ["每月储蓄", money(d.input.monthlySaving)], ["退休后月支出", money(d.input.monthlyExpenseAfterRetirement)], ["退休缺口", money(d.output.gap)]]}/></Panel></Shell>}

function PersonalPage(){const d=personalAssetData; return <Shell><PageHero title="个人资产总览" subtitle="展示总资产、资产结构、未来资产动线，并汇总其他模块结果。"/><section className="grid gap-5 md:grid-cols-4"><KpiCard label="总资产" value={money(d.output.totalAsset)}/><KpiCard label="现金" value={money(d.input.cash)} tone="green"/><KpiCard label="投资资产" value={money(d.input.fund+d.input.stock+d.input.gold)} tone="purple"/><KpiCard label="房产资产" value={money(d.input.property)} tone="orange"/></section><section className="mt-5 grid gap-5 lg:grid-cols-2"><Panel><h2 className="mb-4 text-xl font-bold">资产结构饼图</h2><AllocationPie data={Object.entries(d.output.allocation).map(([name, weight])=>({name, weight}))}/></Panel><Panel><h2 className="mb-4 text-xl font-bold">风险评分与资产动线</h2><p className="mb-4 rounded-xl bg-violet-50 px-4 py-3 font-bold text-violet-700">风险评分：{d.output.riskScore} / 100</p><AreaTrendChart data={d.output.assetCurve}/></Panel></section><InsightCard><h3 className="text-xl font-bold">关联方案</h3><div className="mt-3 flex flex-wrap gap-3"><Link className="rounded-xl border bg-white px-4 py-2 font-bold" href="/modules/buy_rent">买房租房：{d.linkedScenarios.buyRent}</Link><Link className="rounded-xl border bg-white px-4 py-2 font-bold" href="/modules/investment">投资：{d.linkedScenarios.investment}</Link><Link className="rounded-xl border bg-white px-4 py-2 font-bold" href="/modules/retirement">退休：{d.linkedScenarios.retirement}</Link></div></InsightCard></Shell>}
