import {RefreshCw, Star} from 'lucide-react'
import {AreaTrendChart, AllocationPie, LineCompareChart, StackedCostChart} from './Charts'
import {InsightCard, KpiCard, Money, PageHero, Panel, ParameterBar, Shell} from './Ui'
import {buyRentData} from '@/mock/buyRent.mock'
import {investmentData} from '@/mock/investment.mock'
import {livingCostData} from '@/mock/livingCost.mock'
import {retirementData} from '@/mock/retirement.mock'
import {personalAssetData} from '@/mock/personalAsset.mock'
import type {ScenarioModule} from '@/lib/types'

export function FinanceModulePage({module}: {module: ScenarioModule}) {
  if (module === 'buy_rent') return <BuyRentPage />
  if (module === 'investment') return <InvestmentPage />
  if (module === 'living_cost') return <LivingCostPage />
  if (module === 'retirement') return <RetirementPage />
  return <PersonalPage />
}

function BuyRentPage() {const d=buyRentData; return <Shell><PageHero title="买房 vs 租房决策" subtitle="基于您的财务状况与目标，智能对比两种居住方案的长期成本与资产表现" actions={<div className="flex gap-3"><button className="rounded-xl border bg-white px-5 py-3 font-bold"><RefreshCw className="mr-2 inline" size={16}/>重新计算</button><button className="rounded-xl border bg-white px-5 py-3 font-bold"><Star className="mr-2 inline" size={16}/>收藏方案</button></div>}/><section className="grid gap-5 lg:grid-cols-2"><KpiCard label="买房方案 · 长期自有资产" value="¥2,680,000" hint="月供 ¥10,650 / 月；净资产增长 ¥2,440,000"/><KpiCard label="租房方案 · 灵活投资优先" value="¥2,050,000" hint="月租 ¥6,200 / 月；净资产增长 ¥3,210,000" tone="green"/></section><div className="mt-5"><ParameterBar items={[['房价','¥3,000,000'],['首付比例','30%'],['按揭利率','3.85%'],['房价年涨幅','2.0%'],['月租金','¥6,200'],['投资年化收益','6.0%'],['持有/规划年限','30 年']].map(([label,value])=>({label,value}))}/></div><section className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_1fr]"><Panel><h2 className="mb-4 text-xl font-bold">买房净资产 vs 租房投资资产（30 年）</h2><LineCompareChart data={d.output.chart} lines={[{key:'buyNetAsset',name:'买房净资产'},{key:'rentNetAsset',name:'租房投资资产',color:'#10b981'}]}/></Panel><div className="grid gap-5"><Panel><h3 className="font-bold">房产价值曲线</h3><LineCompareChart data={d.output.chart} lines={[{key:'propertyValue',name:'房产价值'}]}/></Panel></div></section><Panel className="mt-5"><table className="w-full text-left text-sm"><tbody>{[['总成本（30年）','¥2,680,000','¥2,050,000'],['最终资产（30年后）','¥5,120,000','¥5,260,000'],['灵活性','较低','高'],['风险','中等','较低']].map(r=><tr className="border-b last:border-0" key={r[0]}><th className="py-3 text-slate-500">{r[0]}</th><td className="font-bold text-blue-600">{r[1]}</td><td className="font-bold text-emerald-600">{r[2]}</td></tr>)}</tbody></table></Panel><InsightCard><h3 className="text-xl font-bold">租房方案更优</h3><p className="mt-2 text-slate-600">在当前假设下，租房并投资的方案在 30 年后可多获得 <b className="text-emerald-600">¥820,000</b> 净资产。</p></InsightCard></Shell>}

function InvestmentPage(){const d=investmentData; return <Shell><PageHero title="投资协助" subtitle="输入金额与偏好，快速生成适合你的投资分配方案"/><section className="grid gap-5 lg:grid-cols-[0.7fr_1.3fr]"><Panel><h2 className="text-xl font-bold">1. 输入你的投资信息</h2><div className="mt-5 space-y-5"><div className="rounded-xl border p-4 text-3xl font-black">¥ 100,000 <span className="text-base font-medium text-slate-500">元</span></div><div className="grid grid-cols-2 gap-3"><button className="rounded-xl border border-blue-400 bg-blue-50 py-3 font-bold text-blue-600">定投（每月投入）</button><button className="rounded-xl border py-3 font-bold">一次性买入</button></div><button className="w-full rounded-xl bg-gradient-to-r from-blue-600 to-violet-600 py-4 font-bold text-white">一键分配</button></div></Panel><Panel><div className="flex justify-between"><h2 className="text-xl font-bold">2. 为你生成的投资分配方案</h2><span className="rounded-xl bg-orange-50 px-3 py-2 text-sm font-bold text-orange-600">风险等级：平衡型</span></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><AllocationPie data={d.scenario.assets.map(a=>({name:a.name,weight:a.weight}))}/><LineCompareChart data={d.output.chart} lines={[{key:'value',name:'定投（每月投入）'},{key:'optimistic',name:'乐观',color:'#8b5cf6'}]}/></div><div className="mt-5 grid gap-4 md:grid-cols-3"><KpiCard label="预计年化区间" value="6.5% ~ 10.5%" tone="green"/><KpiCard label="最大回撤提示" value="-18% ~ -28%" tone="orange"/><KpiCard label="适合人群" value="稳健增值型" tone="purple"/></div></Panel></section><InsightCard><h3 className="text-xl font-bold">AI 总结建议</h3><p className="mt-2 text-slate-600">平衡风险偏好下，通过全球分散配置实现长期稳健增值，建议长期持有并定期再平衡。</p></InsightCard></Shell>}

function LivingCostPage(){const d=livingCostData; return <Shell><PageHero title="不同城市生活成本" subtitle="比较不同城市的居住、饮食、交通与储蓄空间"/><section className="mb-5 flex flex-wrap gap-3">{d.scenario.cities.map(c=><button className="rounded-xl border bg-white px-8 py-3 font-bold text-blue-600" key={c.city}>{c.city}</button>)}</section><Panel><div className="grid gap-6 lg:grid-cols-[1.3fr_1fr]"><div><h2 className="mb-5 text-xl font-bold">月度生活成本对比（基础版）</h2><div className="grid gap-4 md:grid-cols-3">{d.scenario.cities.map(c=>{const total=c.rent+c.food+c.transport+c.taxAndInsurance+c.entertainment+c.other; return <div className="rounded-xl border p-5" key={c.city}><h3 className="text-xl font-bold">{c.city}</h3><p className="mt-3 text-2xl font-black text-blue-600"><Money value={total}/> / 月</p><p className="mt-4 text-sm text-slate-500">预计每月可储蓄：¥{Math.max(0,18000-total).toLocaleString('zh-CN')}</p></div>})}</div></div><StackedCostChart data={d.output.chart}/></div></Panel><InsightCard><h3 className="text-xl font-bold">AI 结论</h3><p className="mt-2 text-slate-600">广州的月度总支出最低，生活成本最具优势；新加坡储蓄金额较高但成本压力更大。</p></InsightCard></Shell>}

function RetirementPage(){const d=retirementData; return <Shell><PageHero title="退休计划" subtitle="估算退休目标、资产积累路径与退休后现金流"/><section className="grid gap-5 lg:grid-cols-[1.1fr_repeat(4,1fr)]"><Panel><h2 className="text-xl font-bold">计划参数</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border p-3">当前年龄：30 岁</div><div className="rounded-xl border p-3">计划退休：55 岁</div><div className="rounded-xl border p-3">每月投入：¥8,000</div><div className="rounded-xl border p-3">已有资产：¥300,000</div></div></Panel><KpiCard label="退休目标金额" value="¥6,120,000" tone="green"/><KpiCard label="预计可退休年龄" value="55.3 岁"/><KpiCard label="退休后月支出" value="¥15,000" tone="purple"/><KpiCard label="现金流安全度" value="1.42" tone="orange"/></section><section className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><Panel><h2 className="mb-4 text-xl font-bold">资产增长推演</h2><LineCompareChart data={d.output.chart.map(x=>({...x, value:x.asset, conservative:Math.round(x.asset*0.72), optimistic:Math.round(x.asset*1.4)}))} lines={[{key:'optimistic',name:'乐观'},{key:'value',name:'基准'},{key:'conservative',name:'保守',color:'#8b5cf6'}]}/></Panel><Panel><h2 className="text-xl font-bold">不同地区退休成本（每月）</h2><div className="mt-6 grid gap-4 md:grid-cols-3 lg:grid-cols-1">{['中国大陆 ¥15,000','香港 ¥23,000','新加坡 ¥21,000'].map(x=><div className="rounded-xl border p-5 text-center text-xl font-bold" key={x}>{x}</div>)}</div></Panel></section><InsightCard><h3 className="text-xl font-bold">AI 退休摘要</h3><p className="mt-2 text-slate-600">整体上，您的退休计划基本可行；如希望 55 岁退休，建议将月投入提升至 ¥8,900 或延后退休约 4 个月。</p></InsightCard></Shell>}

function PersonalPage(){const d=personalAssetData; return <Shell><PageHero title="个人资产总览" subtitle="当前资产结构、风险评分与未来资产动线"/><section className="grid gap-5 md:grid-cols-4"><KpiCard label="总资产" value="¥1,830,000"/><KpiCard label="净资产" value="¥1,500,000" tone="green"/><KpiCard label="总负债" value="¥330,000" tone="orange"/><KpiCard label="风险评分" value="58 / 100" tone="purple"/></section><section className="mt-5 grid gap-5 lg:grid-cols-2"><Panel><h2 className="mb-4 text-xl font-bold">资产结构</h2><AllocationPie data={Object.entries(d.output.allocation).map(([name, weight])=>({name, weight}))}/></Panel><Panel><h2 className="mb-4 text-xl font-bold">未来资产动线</h2><AreaTrendChart data={d.output.assetCurve}/></Panel></section><InsightCard><h3 className="text-xl font-bold">关联方案</h3><p className="mt-2 text-slate-600">已关联买房租房、投资和退休方案，可继续跳转模块查看完整决策。</p></InsightCard></Shell>}
