import type {ReactNode} from 'react'
import {cn} from '@/lib/utils'

export const pageFrame = 'mx-auto w-[94vw] py-8 md:w-[95vw] md:py-10'
export const panelClass = 'rounded-[8px] border border-slate-200/80 bg-white shadow-[0_18px_45px_rgba(67,85,120,0.07)]'

export function Shell({children}: {children: ReactNode}) {return <main className="min-h-screen bg-[#f7f9ff] text-slate-950"><div className={pageFrame}>{children}</div></main>}
export function PageHero({title, subtitle, actions}: {title: string; subtitle: string; actions?: ReactNode}) {return <section className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h1 className="text-[34px] font-black leading-tight tracking-normal text-slate-950 md:text-[44px] lg:text-[48px]">{title}</h1><p className="mt-3 text-base text-slate-600 md:text-lg">{subtitle}</p></div>{actions}</section>}
export function Panel({children, className}: {children: ReactNode; className?: string}) {return <section className={cn(panelClass, 'p-5 md:p-6', className)}>{children}</section>}
export function KpiCard({label, value, hint, tone='blue'}: {label: string; value: string; hint?: string; tone?: 'blue'|'green'|'purple'|'orange'}) {const colors={blue:'text-blue-600 bg-blue-50',green:'text-emerald-600 bg-emerald-50',purple:'text-violet-600 bg-violet-50',orange:'text-orange-600 bg-orange-50'}; return <Panel className="min-h-36"><div className={cn('mb-5 inline-flex rounded-[8px] px-3 py-2 text-sm font-bold', colors[tone])}>{label}</div><div className="text-2xl font-black md:text-3xl">{value}</div>{hint && <p className="mt-3 text-sm text-slate-500">{hint}</p>}</Panel>}
export function ParameterBar({items}: {items: {label: string; value: string}[]}) {return <Panel className="grid gap-4 md:grid-cols-4 lg:grid-cols-8">{items.map((item)=><label key={item.label} className="text-sm text-slate-500"><span>{item.label}</span><div className="mt-2 rounded-[8px] border bg-slate-50 px-3 py-3 font-semibold text-slate-900">{item.value}</div></label>)}</Panel>}
export function InsightCard({children}: {children: ReactNode}) {return <Panel className="border-violet-200 bg-gradient-to-r from-white to-violet-50"><div className="flex gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-[8px] bg-gradient-to-br from-blue-500 to-violet-600 font-black text-white">AI</div><div>{children}</div></div></Panel>}
export function Money({value}: {value: number}) {return <>¥{value.toLocaleString('zh-CN')}</>}

export function ScenarioTabs({items, active}: {items: string[]; active: string}) {return <div className="flex gap-3 overflow-x-auto pb-1">{items.map((item)=><button key={item} className={cn('shrink-0 rounded-[8px] border px-6 py-3 font-bold transition', item===active ? 'border-indigo-500 bg-indigo-50 text-indigo-700 shadow-[0_8px_20px_rgba(79,70,229,0.12)]' : 'bg-white text-slate-600 hover:border-indigo-300')}>{item}</button>)}</div>}
export function DataTable({headers, rows}: {headers: string[]; rows: (string | number)[][]}) {return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b bg-slate-50">{headers.map((header)=><th key={header} className="px-4 py-3 font-bold text-slate-600">{header}</th>)}</tr></thead><tbody>{rows.map((row, index)=><tr className="border-b last:border-0" key={index}>{row.map((cell, cellIndex)=><td key={`${index}-${cellIndex}`} className={cn('px-4 py-3', cellIndex === 0 ? 'font-bold text-slate-700' : 'text-slate-600')}>{cell}</td>)}</tr>)}</tbody></table></div>}
