import type {ReactNode} from 'react'
import {cn} from '@/lib/utils'

export function Shell({children}: {children: ReactNode}) {return <main className="min-h-screen bg-[#f7f9ff] text-slate-950"><div className="mx-auto max-w-7xl px-6 py-8">{children}</div></main>}
export function PageHero({title, subtitle, actions}: {title: string; subtitle: string; actions?: ReactNode}) {return <section className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h1 className="text-4xl font-black tracking-tight lg:text-5xl">{title}</h1><p className="mt-3 text-lg text-slate-600">{subtitle}</p></div>{actions}</section>}
export function Panel({children, className}: {children: ReactNode; className?: string}) {return <section className={cn('rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_18px_55px_rgba(65,80,120,0.08)]', className)}>{children}</section>}
export function KpiCard({label, value, hint, tone='blue'}: {label: string; value: string; hint?: string; tone?: 'blue'|'green'|'purple'|'orange'}) {const colors={blue:'text-blue-600 bg-blue-50',green:'text-emerald-600 bg-emerald-50',purple:'text-violet-600 bg-violet-50',orange:'text-orange-600 bg-orange-50'}; return <Panel className="min-h-36"><div className={cn('mb-5 inline-flex rounded-2xl px-3 py-2 text-sm font-bold', colors[tone])}>{label}</div><div className="text-3xl font-black">{value}</div>{hint && <p className="mt-3 text-sm text-slate-500">{hint}</p>}</Panel>}
export function ParameterBar({items}: {items: {label: string; value: string}[]}) {return <Panel className="grid gap-4 md:grid-cols-4 lg:grid-cols-8">{items.map((item)=><label key={item.label} className="text-sm text-slate-500"><span>{item.label}</span><div className="mt-2 rounded-lg border bg-slate-50 px-3 py-3 font-semibold text-slate-900">{item.value}</div></label>)}</Panel>}
export function InsightCard({children}: {children: ReactNode}) {return <Panel className="border-violet-200 bg-gradient-to-r from-white to-violet-50"><div className="flex gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-blue-500 to-violet-600 font-black text-white">AI</div><div>{children}</div></div></Panel>}
export function Money({value}: {value: number}) {return <>¥{value.toLocaleString('zh-CN')}</>}
