import Link from 'next/link'
import {ArrowRight, BarChart3, Building2, Home, Sparkles, Umbrella} from 'lucide-react'
import {homeData} from '@/mock/home.mock'
import {Panel, Shell, Money, InsightCard} from '@/components/scenario-finance/Ui'

const icons = {buy_rent: Home, investment: BarChart3, living_cost: Building2, retirement: Umbrella}

export default function ScenarioHomePage() {
  return <Shell><section className="grid items-center gap-8 lg:grid-cols-[1.1fr_0.9fr]"><div><h1 className="text-5xl font-black leading-tight lg:text-6xl">把复杂决策，<br/>变成<span className="text-blue-600">清晰方案。</span></h1><p className="mt-5 text-xl text-slate-600">多维度数据分析，帮你做出更明智的财务决策。</p><div className="mt-8 flex flex-wrap gap-4 text-sm text-slate-600"><span className="rounded-full border bg-white px-4 py-2">买房还是租房</span><span className="rounded-full border bg-white px-4 py-2">10 万怎么配置</span><span className="rounded-full border bg-white px-4 py-2">深圳还是新加坡</span><span className="rounded-full border bg-white px-4 py-2">几岁可以退休</span></div></div><Panel className="relative min-h-72 overflow-hidden bg-gradient-to-br from-blue-50 to-violet-100"><Sparkles className="absolute right-10 top-10 text-blue-500" size={64}/><div className="absolute bottom-8 left-8 right-8 grid grid-cols-3 gap-4"><div className="h-24 rounded-2xl bg-white/70"/><div className="h-36 rounded-2xl bg-white/80"/><div className="h-28 rounded-2xl bg-white/70"/></div></Panel></section><section className="mt-8 grid gap-4 lg:grid-cols-4">{homeData.moduleCards.map((card)=>{const Icon=icons[card.key]; return <Link href={`/scenario-finance/modules/${card.key}`} key={card.key}><Panel className="h-full transition hover:-translate-y-1 hover:border-blue-300"><Icon className="mb-5 text-blue-600" size={36}/><h2 className="text-xl font-bold">{card.title}</h2><p className="mt-2 text-sm text-slate-500">{card.subtitle}</p><p className="mt-4 text-sm font-bold text-emerald-600">{card.status}</p></Panel></Link>})}</section><section className="mt-6 grid gap-4 lg:grid-cols-[1fr_2fr]"><Panel><p className="text-slate-500">总资产预览</p><p className="mt-3 text-4xl font-black"><Money value={homeData.totalAsset}/></p></Panel><InsightCard><h3 className="text-xl font-bold">AI 总结</h3><p className="mt-2 text-slate-600">当前方案偏稳健，租房与平衡投资组合在中长期现金流上更有弹性。</p></InsightCard></section><Panel className="mt-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">最近方案 / 案例库</h2><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">一键生成个性化方案</button></div><div className="mt-5 grid gap-3">{homeData.recentScenarios.map((item)=><Link className="flex items-center justify-between rounded-xl border p-4 hover:bg-slate-50" href={`/scenario-finance/modules/${item.module}`} key={item.id}><span><strong>{item.title}</strong><small className="ml-3 text-slate-500">{item.createdAt}</small></span><ArrowRight size={18}/></Link>)}</div></Panel></Shell>
}
